### ISSUE TITLE
Add delay/not so aggresive changes (or transition, instead of just instant changing)

### ISSUE THREAD

**Issue by riahc3** [BradyBrenot/huestacean#46] opened 2018-03-03 10:29 UTC
I must say; This app is amazing and its really really good.

That being said, a transition mode might be nice.

Right now, in a movie for example, if there is a bright scene, it sets to white. When changing it a dark scene, it sets to dark/turns off. While that is nice and perfect, something that tries to make a transition as fast as  possible would be nice too.

This doesnt make it as "impactful" on the eyes, which might make affect some people.

Would this be possible to implement?

Thanks

**Comment by BradyBrenot** [comment] 2018-03-03 15:12
Dupe of #16

**Closed by BradyBrenot** 2018-03-03 15:12 UTC
Labels: duplicate

**Comment by riahc3** [comment] 2018-03-03 16:26
Sorry for the dupe
